<?php
// auto-generated by sfViewConfigHandler
// date: 2013/11/06 13:17:56
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'GoAbroad.com', false, false);
  $response->addMeta('description', 'GoAbroad.com is a directory of international travel opportunities', false, false);
  $response->addMeta('keywords', 'goabroad, study, travel, volunteer, teach, degree', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('/min/g=clientApp.css', '', array ());
  $response->addJavascript('/min/g=clientApp.js', '', array ());


