<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tblSubject' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thursday, 26 September, 2013 07:42:52 PM PHT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SubjectPeer extends BaseSubjectPeer {

} // SubjectPeer
