<?php

/**
 * Base class that represents a row from the 'tblStudentSchedule' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thursday, 03 October, 2013 06:36:30 PM PHT
 *
 * @package    lib.model.om
 */
abstract class BaseStudentSchedule extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        StudentSchedulePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the student_course_id field.
	 * @var        int
	 */
	protected $student_course_id;

	/**
	 * The value for the day field.
	 * @var        string
	 */
	protected $day;

	/**
	 * The value for the start_hour field.
	 * @var        string
	 */
	protected $start_hour;

	/**
	 * The value for the end_hour field.
	 * @var        string
	 */
	protected $end_hour;

	/**
	 * The value for the subject_id field.
	 * @var        string
	 */
	protected $subject_id;

	/**
	 * The value for the room_id field.
	 * @var        int
	 */
	protected $room_id;

	/**
	 * @var        StudentCourse
	 */
	protected $aStudentCourse;

	/**
	 * @var        Subject
	 */
	protected $aSubject;

	/**
	 * @var        Room
	 */
	protected $aRoom;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'StudentSchedulePeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getID()
	{
		return $this->id;
	}

	/**
	 * Get the [student_course_id] column value.
	 * 
	 * @return     int
	 */
	public function getStudentCourseId()
	{
		return $this->student_course_id;
	}

	/**
	 * Get the [day] column value.
	 * 
	 * @return     string
	 */
	public function getDay()
	{
		return $this->day;
	}

	/**
	 * Get the [optionally formatted] temporal [start_hour] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStartHour($format = 'H:i:s')
	{
		if ($this->start_hour === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->start_hour);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->start_hour, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [end_hour] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getEndHour($format = 'H:i:s')
	{
		if ($this->end_hour === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->end_hour);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->end_hour, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [subject_id] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getSubjectId($format = 'H:i:s')
	{
		if ($this->subject_id === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->subject_id);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->subject_id, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [room_id] column value.
	 * 
	 * @return     int
	 */
	public function getRoomId()
	{
		return $this->room_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setID($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = StudentSchedulePeer::ID;
		}

		return $this;
	} // setID()

	/**
	 * Set the value of [student_course_id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setStudentCourseId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->student_course_id !== $v) {
			$this->student_course_id = $v;
			$this->modifiedColumns[] = StudentSchedulePeer::STUDENT_COURSE_ID;
		}

		if ($this->aStudentCourse !== null && $this->aStudentCourse->getID() !== $v) {
			$this->aStudentCourse = null;
		}

		return $this;
	} // setStudentCourseId()

	/**
	 * Set the value of [day] column.
	 * 
	 * @param      string $v new value
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setDay($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->day !== $v) {
			$this->day = $v;
			$this->modifiedColumns[] = StudentSchedulePeer::DAY;
		}

		return $this;
	} // setDay()

	/**
	 * Sets the value of [start_hour] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setStartHour($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->start_hour !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->start_hour !== null && $tmpDt = new DateTime($this->start_hour)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->start_hour = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = StudentSchedulePeer::START_HOUR;
			}
		} // if either are not null

		return $this;
	} // setStartHour()

	/**
	 * Sets the value of [end_hour] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setEndHour($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->end_hour !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->end_hour !== null && $tmpDt = new DateTime($this->end_hour)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->end_hour = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = StudentSchedulePeer::END_HOUR;
			}
		} // if either are not null

		return $this;
	} // setEndHour()

	/**
	 * Sets the value of [subject_id] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setSubjectId($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->subject_id !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->subject_id !== null && $tmpDt = new DateTime($this->subject_id)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->subject_id = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = StudentSchedulePeer::SUBJECT_ID;
			}
		} // if either are not null

		if ($this->aSubject !== null && $this->aSubject->getID() !== $v) {
			$this->aSubject = null;
		}

		return $this;
	} // setSubjectId()

	/**
	 * Set the value of [room_id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentSchedule The current object (for fluent API support)
	 */
	public function setRoomId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->room_id !== $v) {
			$this->room_id = $v;
			$this->modifiedColumns[] = StudentSchedulePeer::ROOM_ID;
		}

		if ($this->aRoom !== null && $this->aRoom->getID() !== $v) {
			$this->aRoom = null;
		}

		return $this;
	} // setRoomId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->student_course_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->day = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->start_hour = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->end_hour = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->subject_id = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->room_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = StudentSchedulePeer::NUM_COLUMNS - StudentSchedulePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating StudentSchedule object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aStudentCourse !== null && $this->student_course_id !== $this->aStudentCourse->getID()) {
			$this->aStudentCourse = null;
		}
		if ($this->aSubject !== null && $this->subject_id !== $this->aSubject->getID()) {
			$this->aSubject = null;
		}
		if ($this->aRoom !== null && $this->room_id !== $this->aRoom->getID()) {
			$this->aRoom = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentSchedulePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = StudentSchedulePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aStudentCourse = null;
			$this->aSubject = null;
			$this->aRoom = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentSchedulePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseStudentSchedule:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				StudentSchedulePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseStudentSchedule:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentSchedulePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseStudentSchedule:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseStudentSchedule:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				StudentSchedulePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudentCourse !== null) {
				if ($this->aStudentCourse->isModified() || $this->aStudentCourse->isNew()) {
					$affectedRows += $this->aStudentCourse->save($con);
				}
				$this->setStudentCourse($this->aStudentCourse);
			}

			if ($this->aSubject !== null) {
				if ($this->aSubject->isModified() || $this->aSubject->isNew()) {
					$affectedRows += $this->aSubject->save($con);
				}
				$this->setSubject($this->aSubject);
			}

			if ($this->aRoom !== null) {
				if ($this->aRoom->isModified() || $this->aRoom->isNew()) {
					$affectedRows += $this->aRoom->save($con);
				}
				$this->setRoom($this->aRoom);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = StudentSchedulePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = StudentSchedulePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setID($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += StudentSchedulePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudentCourse !== null) {
				if (!$this->aStudentCourse->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aStudentCourse->getValidationFailures());
				}
			}

			if ($this->aSubject !== null) {
				if (!$this->aSubject->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSubject->getValidationFailures());
				}
			}

			if ($this->aRoom !== null) {
				if (!$this->aRoom->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRoom->getValidationFailures());
				}
			}


			if (($retval = StudentSchedulePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = StudentSchedulePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getID();
				break;
			case 1:
				return $this->getStudentCourseId();
				break;
			case 2:
				return $this->getDay();
				break;
			case 3:
				return $this->getStartHour();
				break;
			case 4:
				return $this->getEndHour();
				break;
			case 5:
				return $this->getSubjectId();
				break;
			case 6:
				return $this->getRoomId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = StudentSchedulePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getID(),
			$keys[1] => $this->getStudentCourseId(),
			$keys[2] => $this->getDay(),
			$keys[3] => $this->getStartHour(),
			$keys[4] => $this->getEndHour(),
			$keys[5] => $this->getSubjectId(),
			$keys[6] => $this->getRoomId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = StudentSchedulePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setID($value);
				break;
			case 1:
				$this->setStudentCourseId($value);
				break;
			case 2:
				$this->setDay($value);
				break;
			case 3:
				$this->setStartHour($value);
				break;
			case 4:
				$this->setEndHour($value);
				break;
			case 5:
				$this->setSubjectId($value);
				break;
			case 6:
				$this->setRoomId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = StudentSchedulePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setID($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setStudentCourseId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDay($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStartHour($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEndHour($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSubjectId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setRoomId($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(StudentSchedulePeer::DATABASE_NAME);

		if ($this->isColumnModified(StudentSchedulePeer::ID)) $criteria->add(StudentSchedulePeer::ID, $this->id);
		if ($this->isColumnModified(StudentSchedulePeer::STUDENT_COURSE_ID)) $criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->student_course_id);
		if ($this->isColumnModified(StudentSchedulePeer::DAY)) $criteria->add(StudentSchedulePeer::DAY, $this->day);
		if ($this->isColumnModified(StudentSchedulePeer::START_HOUR)) $criteria->add(StudentSchedulePeer::START_HOUR, $this->start_hour);
		if ($this->isColumnModified(StudentSchedulePeer::END_HOUR)) $criteria->add(StudentSchedulePeer::END_HOUR, $this->end_hour);
		if ($this->isColumnModified(StudentSchedulePeer::SUBJECT_ID)) $criteria->add(StudentSchedulePeer::SUBJECT_ID, $this->subject_id);
		if ($this->isColumnModified(StudentSchedulePeer::ROOM_ID)) $criteria->add(StudentSchedulePeer::ROOM_ID, $this->room_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(StudentSchedulePeer::DATABASE_NAME);

		$criteria->add(StudentSchedulePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getID();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setID($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of StudentSchedule (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setStudentCourseId($this->student_course_id);

		$copyObj->setDay($this->day);

		$copyObj->setStartHour($this->start_hour);

		$copyObj->setEndHour($this->end_hour);

		$copyObj->setSubjectId($this->subject_id);

		$copyObj->setRoomId($this->room_id);


		$copyObj->setNew(true);

		$copyObj->setID(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     StudentSchedule Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     StudentSchedulePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new StudentSchedulePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a StudentCourse object.
	 *
	 * @param      StudentCourse $v
	 * @return     StudentSchedule The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setStudentCourse(StudentCourse $v = null)
	{
		if ($v === null) {
			$this->setStudentCourseId(NULL);
		} else {
			$this->setStudentCourseId($v->getID());
		}

		$this->aStudentCourse = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the StudentCourse object, it will not be re-added.
		if ($v !== null) {
			$v->addStudentSchedule($this);
		}

		return $this;
	}


	/**
	 * Get the associated StudentCourse object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     StudentCourse The associated StudentCourse object.
	 * @throws     PropelException
	 */
	public function getStudentCourse(PropelPDO $con = null)
	{
		if ($this->aStudentCourse === null && ($this->student_course_id !== null)) {
			$this->aStudentCourse = StudentCoursePeer::retrieveByPk($this->student_course_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aStudentCourse->addStudentSchedules($this);
			 */
		}
		return $this->aStudentCourse;
	}

	/**
	 * Declares an association between this object and a Subject object.
	 *
	 * @param      Subject $v
	 * @return     StudentSchedule The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSubject(Subject $v = null)
	{
		if ($v === null) {
			$this->setSubjectId(NULL);
		} else {
			$this->setSubjectId($v->getID());
		}

		$this->aSubject = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Subject object, it will not be re-added.
		if ($v !== null) {
			$v->addStudentSchedule($this);
		}

		return $this;
	}


	/**
	 * Get the associated Subject object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Subject The associated Subject object.
	 * @throws     PropelException
	 */
	public function getSubject(PropelPDO $con = null)
	{
		if ($this->aSubject === null && (($this->subject_id !== "" && $this->subject_id !== null))) {
			$this->aSubject = SubjectPeer::retrieveByPk($this->subject_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSubject->addStudentSchedules($this);
			 */
		}
		return $this->aSubject;
	}

	/**
	 * Declares an association between this object and a Room object.
	 *
	 * @param      Room $v
	 * @return     StudentSchedule The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRoom(Room $v = null)
	{
		if ($v === null) {
			$this->setRoomId(NULL);
		} else {
			$this->setRoomId($v->getID());
		}

		$this->aRoom = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Room object, it will not be re-added.
		if ($v !== null) {
			$v->addStudentSchedule($this);
		}

		return $this;
	}


	/**
	 * Get the associated Room object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Room The associated Room object.
	 * @throws     PropelException
	 */
	public function getRoom(PropelPDO $con = null)
	{
		if ($this->aRoom === null && ($this->room_id !== null)) {
			$this->aRoom = RoomPeer::retrieveByPk($this->room_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRoom->addStudentSchedules($this);
			 */
		}
		return $this->aRoom;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aStudentCourse = null;
			$this->aSubject = null;
			$this->aRoom = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseStudentSchedule:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseStudentSchedule::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseStudentSchedule
