<?php

/**
 * Base class that represents a row from the 'tblStudentCourse' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thursday, 03 October, 2013 06:36:29 PM PHT
 *
 * @package    lib.model.om
 */
abstract class BaseStudentCourse extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        StudentCoursePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the student_id field.
	 * @var        int
	 */
	protected $student_id;

	/**
	 * The value for the section field.
	 * @var        string
	 */
	protected $section;

	/**
	 * The value for the course_id field.
	 * @var        int
	 */
	protected $course_id;

	/**
	 * The value for the year_level_id field.
	 * @var        int
	 */
	protected $year_level_id;

	/**
	 * The value for the school_year field.
	 * @var        string
	 */
	protected $school_year;

	/**
	 * The value for the is_active field.
	 * @var        boolean
	 */
	protected $is_active;

	/**
	 * @var        Student
	 */
	protected $aStudent;

	/**
	 * @var        Course
	 */
	protected $aCourse;

	/**
	 * @var        YearLevel
	 */
	protected $aYearLevel;

	/**
	 * @var        array StudentSchedule[] Collection to store aggregation of StudentSchedule objects.
	 */
	protected $collStudentSchedules;

	/**
	 * @var        Criteria The criteria used to select the current contents of collStudentSchedules.
	 */
	private $lastStudentScheduleCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'StudentCoursePeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getID()
	{
		return $this->id;
	}

	/**
	 * Get the [student_id] column value.
	 * 
	 * @return     int
	 */
	public function getStudentId()
	{
		return $this->student_id;
	}

	/**
	 * Get the [section] column value.
	 * 
	 * @return     string
	 */
	public function getSection()
	{
		return $this->section;
	}

	/**
	 * Get the [course_id] column value.
	 * 
	 * @return     int
	 */
	public function getCourseId()
	{
		return $this->course_id;
	}

	/**
	 * Get the [year_level_id] column value.
	 * 
	 * @return     int
	 */
	public function getYearLevelId()
	{
		return $this->year_level_id;
	}

	/**
	 * Get the [optionally formatted] temporal [school_year] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getSchoolYear($format = 'Y-m-d H:i:s')
	{
		if ($this->school_year === null) {
			return null;
		}


		if ($this->school_year === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->school_year);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->school_year, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [is_active] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsActive()
	{
		return $this->is_active;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setID($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = StudentCoursePeer::ID;
		}

		return $this;
	} // setID()

	/**
	 * Set the value of [student_id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setStudentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->student_id !== $v) {
			$this->student_id = $v;
			$this->modifiedColumns[] = StudentCoursePeer::STUDENT_ID;
		}

		if ($this->aStudent !== null && $this->aStudent->getID() !== $v) {
			$this->aStudent = null;
		}

		return $this;
	} // setStudentId()

	/**
	 * Set the value of [section] column.
	 * 
	 * @param      string $v new value
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setSection($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->section !== $v) {
			$this->section = $v;
			$this->modifiedColumns[] = StudentCoursePeer::SECTION;
		}

		return $this;
	} // setSection()

	/**
	 * Set the value of [course_id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setCourseId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->course_id !== $v) {
			$this->course_id = $v;
			$this->modifiedColumns[] = StudentCoursePeer::COURSE_ID;
		}

		if ($this->aCourse !== null && $this->aCourse->getID() !== $v) {
			$this->aCourse = null;
		}

		return $this;
	} // setCourseId()

	/**
	 * Set the value of [year_level_id] column.
	 * 
	 * @param      int $v new value
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setYearLevelId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->year_level_id !== $v) {
			$this->year_level_id = $v;
			$this->modifiedColumns[] = StudentCoursePeer::YEAR_LEVEL_ID;
		}

		if ($this->aYearLevel !== null && $this->aYearLevel->getID() !== $v) {
			$this->aYearLevel = null;
		}

		return $this;
	} // setYearLevelId()

	/**
	 * Sets the value of [school_year] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setSchoolYear($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->school_year !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->school_year !== null && $tmpDt = new DateTime($this->school_year)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->school_year = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = StudentCoursePeer::SCHOOL_YEAR;
			}
		} // if either are not null

		return $this;
	} // setSchoolYear()

	/**
	 * Set the value of [is_active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     StudentCourse The current object (for fluent API support)
	 */
	public function setIsActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_active !== $v) {
			$this->is_active = $v;
			$this->modifiedColumns[] = StudentCoursePeer::IS_ACTIVE;
		}

		return $this;
	} // setIsActive()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->student_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->section = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->course_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->year_level_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->school_year = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->is_active = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = StudentCoursePeer::NUM_COLUMNS - StudentCoursePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating StudentCourse object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aStudent !== null && $this->student_id !== $this->aStudent->getID()) {
			$this->aStudent = null;
		}
		if ($this->aCourse !== null && $this->course_id !== $this->aCourse->getID()) {
			$this->aCourse = null;
		}
		if ($this->aYearLevel !== null && $this->year_level_id !== $this->aYearLevel->getID()) {
			$this->aYearLevel = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentCoursePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = StudentCoursePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aStudent = null;
			$this->aCourse = null;
			$this->aYearLevel = null;
			$this->collStudentSchedules = null;
			$this->lastStudentScheduleCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentCoursePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseStudentCourse:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				StudentCoursePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseStudentCourse:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentCoursePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseStudentCourse:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseStudentCourse:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				StudentCoursePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudent !== null) {
				if ($this->aStudent->isModified() || $this->aStudent->isNew()) {
					$affectedRows += $this->aStudent->save($con);
				}
				$this->setStudent($this->aStudent);
			}

			if ($this->aCourse !== null) {
				if ($this->aCourse->isModified() || $this->aCourse->isNew()) {
					$affectedRows += $this->aCourse->save($con);
				}
				$this->setCourse($this->aCourse);
			}

			if ($this->aYearLevel !== null) {
				if ($this->aYearLevel->isModified() || $this->aYearLevel->isNew()) {
					$affectedRows += $this->aYearLevel->save($con);
				}
				$this->setYearLevel($this->aYearLevel);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = StudentCoursePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = StudentCoursePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setID($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += StudentCoursePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collStudentSchedules !== null) {
				foreach ($this->collStudentSchedules as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudent !== null) {
				if (!$this->aStudent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aStudent->getValidationFailures());
				}
			}

			if ($this->aCourse !== null) {
				if (!$this->aCourse->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCourse->getValidationFailures());
				}
			}

			if ($this->aYearLevel !== null) {
				if (!$this->aYearLevel->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aYearLevel->getValidationFailures());
				}
			}


			if (($retval = StudentCoursePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collStudentSchedules !== null) {
					foreach ($this->collStudentSchedules as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = StudentCoursePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getID();
				break;
			case 1:
				return $this->getStudentId();
				break;
			case 2:
				return $this->getSection();
				break;
			case 3:
				return $this->getCourseId();
				break;
			case 4:
				return $this->getYearLevelId();
				break;
			case 5:
				return $this->getSchoolYear();
				break;
			case 6:
				return $this->getIsActive();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = StudentCoursePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getID(),
			$keys[1] => $this->getStudentId(),
			$keys[2] => $this->getSection(),
			$keys[3] => $this->getCourseId(),
			$keys[4] => $this->getYearLevelId(),
			$keys[5] => $this->getSchoolYear(),
			$keys[6] => $this->getIsActive(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = StudentCoursePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setID($value);
				break;
			case 1:
				$this->setStudentId($value);
				break;
			case 2:
				$this->setSection($value);
				break;
			case 3:
				$this->setCourseId($value);
				break;
			case 4:
				$this->setYearLevelId($value);
				break;
			case 5:
				$this->setSchoolYear($value);
				break;
			case 6:
				$this->setIsActive($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = StudentCoursePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setID($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setStudentId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSection($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCourseId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setYearLevelId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSchoolYear($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIsActive($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(StudentCoursePeer::DATABASE_NAME);

		if ($this->isColumnModified(StudentCoursePeer::ID)) $criteria->add(StudentCoursePeer::ID, $this->id);
		if ($this->isColumnModified(StudentCoursePeer::STUDENT_ID)) $criteria->add(StudentCoursePeer::STUDENT_ID, $this->student_id);
		if ($this->isColumnModified(StudentCoursePeer::SECTION)) $criteria->add(StudentCoursePeer::SECTION, $this->section);
		if ($this->isColumnModified(StudentCoursePeer::COURSE_ID)) $criteria->add(StudentCoursePeer::COURSE_ID, $this->course_id);
		if ($this->isColumnModified(StudentCoursePeer::YEAR_LEVEL_ID)) $criteria->add(StudentCoursePeer::YEAR_LEVEL_ID, $this->year_level_id);
		if ($this->isColumnModified(StudentCoursePeer::SCHOOL_YEAR)) $criteria->add(StudentCoursePeer::SCHOOL_YEAR, $this->school_year);
		if ($this->isColumnModified(StudentCoursePeer::IS_ACTIVE)) $criteria->add(StudentCoursePeer::IS_ACTIVE, $this->is_active);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(StudentCoursePeer::DATABASE_NAME);

		$criteria->add(StudentCoursePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getID();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setID($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of StudentCourse (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setStudentId($this->student_id);

		$copyObj->setSection($this->section);

		$copyObj->setCourseId($this->course_id);

		$copyObj->setYearLevelId($this->year_level_id);

		$copyObj->setSchoolYear($this->school_year);

		$copyObj->setIsActive($this->is_active);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getStudentSchedules() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addStudentSchedule($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setID(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     StudentCourse Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     StudentCoursePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new StudentCoursePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Student object.
	 *
	 * @param      Student $v
	 * @return     StudentCourse The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setStudent(Student $v = null)
	{
		if ($v === null) {
			$this->setStudentId(NULL);
		} else {
			$this->setStudentId($v->getID());
		}

		$this->aStudent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Student object, it will not be re-added.
		if ($v !== null) {
			$v->addStudentCourse($this);
		}

		return $this;
	}


	/**
	 * Get the associated Student object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Student The associated Student object.
	 * @throws     PropelException
	 */
	public function getStudent(PropelPDO $con = null)
	{
		if ($this->aStudent === null && ($this->student_id !== null)) {
			$this->aStudent = StudentPeer::retrieveByPk($this->student_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aStudent->addStudentCourses($this);
			 */
		}
		return $this->aStudent;
	}

	/**
	 * Declares an association between this object and a Course object.
	 *
	 * @param      Course $v
	 * @return     StudentCourse The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCourse(Course $v = null)
	{
		if ($v === null) {
			$this->setCourseId(NULL);
		} else {
			$this->setCourseId($v->getID());
		}

		$this->aCourse = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Course object, it will not be re-added.
		if ($v !== null) {
			$v->addStudentCourse($this);
		}

		return $this;
	}


	/**
	 * Get the associated Course object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Course The associated Course object.
	 * @throws     PropelException
	 */
	public function getCourse(PropelPDO $con = null)
	{
		if ($this->aCourse === null && ($this->course_id !== null)) {
			$this->aCourse = CoursePeer::retrieveByPk($this->course_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCourse->addStudentCourses($this);
			 */
		}
		return $this->aCourse;
	}

	/**
	 * Declares an association between this object and a YearLevel object.
	 *
	 * @param      YearLevel $v
	 * @return     StudentCourse The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setYearLevel(YearLevel $v = null)
	{
		if ($v === null) {
			$this->setYearLevelId(NULL);
		} else {
			$this->setYearLevelId($v->getID());
		}

		$this->aYearLevel = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the YearLevel object, it will not be re-added.
		if ($v !== null) {
			$v->addStudentCourse($this);
		}

		return $this;
	}


	/**
	 * Get the associated YearLevel object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     YearLevel The associated YearLevel object.
	 * @throws     PropelException
	 */
	public function getYearLevel(PropelPDO $con = null)
	{
		if ($this->aYearLevel === null && ($this->year_level_id !== null)) {
			$this->aYearLevel = YearLevelPeer::retrieveByPk($this->year_level_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aYearLevel->addStudentCourses($this);
			 */
		}
		return $this->aYearLevel;
	}

	/**
	 * Clears out the collStudentSchedules collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addStudentSchedules()
	 */
	public function clearStudentSchedules()
	{
		$this->collStudentSchedules = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collStudentSchedules collection (array).
	 *
	 * By default this just sets the collStudentSchedules collection to an empty array (like clearcollStudentSchedules());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initStudentSchedules()
	{
		$this->collStudentSchedules = array();
	}

	/**
	 * Gets an array of StudentSchedule objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this StudentCourse has previously been saved, it will retrieve
	 * related StudentSchedules from storage. If this StudentCourse is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array StudentSchedule[]
	 * @throws     PropelException
	 */
	public function getStudentSchedules($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentCoursePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStudentSchedules === null) {
			if ($this->isNew()) {
			   $this->collStudentSchedules = array();
			} else {

				$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

				StudentSchedulePeer::addSelectColumns($criteria);
				$this->collStudentSchedules = StudentSchedulePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

				StudentSchedulePeer::addSelectColumns($criteria);
				if (!isset($this->lastStudentScheduleCriteria) || !$this->lastStudentScheduleCriteria->equals($criteria)) {
					$this->collStudentSchedules = StudentSchedulePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastStudentScheduleCriteria = $criteria;
		return $this->collStudentSchedules;
	}

	/**
	 * Returns the number of related StudentSchedule objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related StudentSchedule objects.
	 * @throws     PropelException
	 */
	public function countStudentSchedules(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentCoursePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collStudentSchedules === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

				$count = StudentSchedulePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

				if (!isset($this->lastStudentScheduleCriteria) || !$this->lastStudentScheduleCriteria->equals($criteria)) {
					$count = StudentSchedulePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collStudentSchedules);
				}
			} else {
				$count = count($this->collStudentSchedules);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a StudentSchedule object to this object
	 * through the StudentSchedule foreign key attribute.
	 *
	 * @param      StudentSchedule $l StudentSchedule
	 * @return     void
	 * @throws     PropelException
	 */
	public function addStudentSchedule(StudentSchedule $l)
	{
		if ($this->collStudentSchedules === null) {
			$this->initStudentSchedules();
		}
		if (!in_array($l, $this->collStudentSchedules, true)) { // only add it if the **same** object is not already associated
			array_push($this->collStudentSchedules, $l);
			$l->setStudentCourse($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this StudentCourse is new, it will return
	 * an empty collection; or if this StudentCourse has previously
	 * been saved, it will retrieve related StudentSchedules from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in StudentCourse.
	 */
	public function getStudentSchedulesJoinSubject($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentCoursePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStudentSchedules === null) {
			if ($this->isNew()) {
				$this->collStudentSchedules = array();
			} else {

				$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

				$this->collStudentSchedules = StudentSchedulePeer::doSelectJoinSubject($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

			if (!isset($this->lastStudentScheduleCriteria) || !$this->lastStudentScheduleCriteria->equals($criteria)) {
				$this->collStudentSchedules = StudentSchedulePeer::doSelectJoinSubject($criteria, $con, $join_behavior);
			}
		}
		$this->lastStudentScheduleCriteria = $criteria;

		return $this->collStudentSchedules;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this StudentCourse is new, it will return
	 * an empty collection; or if this StudentCourse has previously
	 * been saved, it will retrieve related StudentSchedules from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in StudentCourse.
	 */
	public function getStudentSchedulesJoinRoom($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentCoursePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStudentSchedules === null) {
			if ($this->isNew()) {
				$this->collStudentSchedules = array();
			} else {

				$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

				$this->collStudentSchedules = StudentSchedulePeer::doSelectJoinRoom($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(StudentSchedulePeer::STUDENT_COURSE_ID, $this->id);

			if (!isset($this->lastStudentScheduleCriteria) || !$this->lastStudentScheduleCriteria->equals($criteria)) {
				$this->collStudentSchedules = StudentSchedulePeer::doSelectJoinRoom($criteria, $con, $join_behavior);
			}
		}
		$this->lastStudentScheduleCriteria = $criteria;

		return $this->collStudentSchedules;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collStudentSchedules) {
				foreach ((array) $this->collStudentSchedules as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collStudentSchedules = null;
			$this->aStudent = null;
			$this->aCourse = null;
			$this->aYearLevel = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseStudentCourse:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseStudentCourse::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseStudentCourse
