<?php


/**
 * This class defines the structure of the 'tblStudentCourse' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thursday, 03 October, 2013 06:36:29 PM PHT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StudentCourseTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StudentCourseTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tblStudentCourse');
		$this->setPhpName('StudentCourse');
		$this->setClassname('StudentCourse');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'ID', 'INTEGER', true, null, null);
		$this->addForeignKey('STUDENT_ID', 'StudentId', 'INTEGER', 'tblStudent', 'ID', false, null, null);
		$this->addColumn('SECTION', 'Section', 'VARCHAR', false, 255, null);
		$this->addForeignKey('COURSE_ID', 'CourseId', 'INTEGER', 'tblCourse', 'ID', false, null, null);
		$this->addForeignKey('YEAR_LEVEL_ID', 'YearLevelId', 'INTEGER', 'tblYearLevel', 'ID', false, null, null);
		$this->addColumn('SCHOOL_YEAR', 'SchoolYear', 'TIMESTAMP', false, null, null);
		$this->addColumn('IS_ACTIVE', 'IsActive', 'BOOLEAN', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Student', 'Student', RelationMap::MANY_TO_ONE, array('student_id' => 'id', ), null, null);
    $this->addRelation('Course', 'Course', RelationMap::MANY_TO_ONE, array('course_id' => 'id', ), null, null);
    $this->addRelation('YearLevel', 'YearLevel', RelationMap::MANY_TO_ONE, array('year_level_id' => 'id', ), null, null);
    $this->addRelation('StudentSchedule', 'StudentSchedule', RelationMap::ONE_TO_MANY, array('id' => 'student_course_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // StudentCourseTableMap
