<?php


/**
 * This class defines the structure of the 'tblStudentSchedule' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thursday, 03 October, 2013 06:36:30 PM PHT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StudentScheduleTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StudentScheduleTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tblStudentSchedule');
		$this->setPhpName('StudentSchedule');
		$this->setClassname('StudentSchedule');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'ID', 'INTEGER', true, null, null);
		$this->addForeignKey('STUDENT_COURSE_ID', 'StudentCourseId', 'INTEGER', 'tblStudentCourse', 'ID', false, null, null);
		$this->addColumn('DAY', 'Day', 'VARCHAR', false, 20, null);
		$this->addColumn('START_HOUR', 'StartHour', 'TIME', false, null, null);
		$this->addColumn('END_HOUR', 'EndHour', 'TIME', false, null, null);
		$this->addForeignKey('SUBJECT_ID', 'SubjectId', 'TIME', 'tblSubject', 'ID', false, null, null);
		$this->addForeignKey('ROOM_ID', 'RoomId', 'INTEGER', 'tblRoom', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('StudentCourse', 'StudentCourse', RelationMap::MANY_TO_ONE, array('student_course_id' => 'id', ), null, null);
    $this->addRelation('Subject', 'Subject', RelationMap::MANY_TO_ONE, array('subject_id' => 'id', ), null, null);
    $this->addRelation('Room', 'Room', RelationMap::MANY_TO_ONE, array('room_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // StudentScheduleTableMap
