<?php


/**
 * This class defines the structure of the 'tblYearLevel' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thursday, 03 October, 2013 06:36:30 PM PHT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class YearLevelTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.YearLevelTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tblYearLevel');
		$this->setPhpName('YearLevel');
		$this->setClassname('YearLevel');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'ID', 'INTEGER', true, null, null);
		$this->addColumn('YEAR_LEVEL', 'YearLevel', 'VARCHAR', false, 255, null);
		$this->addColumn('SEMESTER', 'Semester', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('StudentCourse', 'StudentCourse', RelationMap::ONE_TO_MANY, array('id' => 'year_level_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // YearLevelTableMap
